export { default as Alert } from "./Alert/Alert";
export { default as Button } from "./Button/Button";
export { default as Card } from "./Card/Card";
export { default as Comment } from "./Comment/Comment";
export { default as Dropdown } from "./Dropdown/Dropdown";
export { default as Inputs } from "./Inputs/Inputs";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Search } from "./Search/Search";
// export { default as Loader } from "./Loader/Loader";
export { default as Table } from "./Table/Table";
